version: "3.7"

services:
  http-clustering:
    build:
      context: .
      dockerfile: docker/debian/Dockerfile
    image: http-clustering/notebook:1.0
    container_name: http-clustering
    volumes:
      - "./data:/app/data"
      - "./results:/app/results"
    ports:
      - "8888:8888"